version: 2

sources:
  - name: raw
    description: alias of the "gz_raw_data" dataset in BigQuery which includes all raw data of the greenweez company
    schema: gz_raw_data
    tables:
      - name: sales
        description: list of the sales
        identifier: raw_gz_sales
      - name: product
        description: list of the products 
        identifier: raw_gz_product
      - name: ship
        description: list of the shipping details by order_id
        identifier: raw_gz_ship
